let products = [
    {
        id: 1,
        name: "Smartphone X",
        brand: "TechCo",
        category: "Smartphones",
        price: 799.99,
        currency: "USD",
        stock: 100,
        rating: 4.5,
        releaseDate: "2023-09-15",
        specs: {
            screenSize: 6.5,
            resolution: "2400x1080",
            processor: "Octa-core 2.8 GHz",
            ram: 8,
            storage: 128,
            camera: {
                rear: "Triple 64MP + 12MP + 5MP",
                front: "32MP",
            },
            battery: 4500,
        },
        features: ["5G", "Wireless Charging", "Water Resistant"],
        colors: ["Black", "White", "Blue"],
        mainImage: "https://images.fonearena.com/blog/wp-content/uploads/2021/06/TECNO-PHANTOM-X-1.jpg",
        subImages: [
            "https://images.hindustantimes.com/tech/htmobile4/P36214/hqImage/145275-v4-tecno-phantom-x-mobile-phone-hres-1.jpg?impolicy=new-ht-20210112&width=500&height=500",
            "https://images.hindustantimes.com/tech/htmobile4/P36214/hqImage/145275-v4-tecno-phantom-x-mobile-phone-hres-2.jpg?impolicy=new-ht-20210112&width=500&height=500",
            "https://images.hindustantimes.com/tech/htmobile4/P36214/hqImage/145275-v4-tecno-phantom-x-mobile-phone-hres-8.jpg?impolicy=new-ht-20210112&width=500&height=500",
        ],
        description:
            "Experience the cutting-edge technology with Smartphone X. Featuring a powerful processor, stunning camera, and 5G capabilities.",
    },
    {
        id: 2,
        name: "4K Smart TV",
        brand: "ViewTech",
        category: "Televisions",
        price: 1299.99,
        currency: "USD",
        stock: 50,
        rating: 4.7,
        releaseDate: "2023-11-01",
        specs: {
            screenSize: 55,
            resolution: "3840x2160",
            refreshRate: 120,
            hdrSupport: "HDR10+",
            smartPlatform: "AndroidTV",
        },
        features: ["Voice Control", "Dolby Atmos", "Bluetooth"],
        colors: ["Black"],
        mainImage: "https://m.media-amazon.com/images/I/71SMeatgB7L._SL1500_.jpg",
        subImages: [
            "https://m.media-amazon.com/images/I/71OmFJw214L._SL1500_.jpg",
            "https://m.media-amazon.com/images/I/71V1aZjNSpL._SL1500_.jpg",
            "https://m.media-amazon.com/images/I/61vFHGRIziL._SL1500_.jpg",
        ],
        description:
            "Immerse yourself in stunning 4K resolution with this Smart TV. Enjoy a cinematic experience with HDR support and Dolby Atmos sound.",
    },
    {
        id: 3,
        name: "Wireless Earbuds Pro",
        brand: "AudioMax",
        category: "Audio",
        price: 199.99,
        currency: "USD",
        stock: 200,
        rating: 4.6,
        releaseDate: "2023-10-01",
        specs: {
            batteryLife: "6 hours (24 with case)",
            driver: "11mm dynamic",
            noiseReduction: "Active Noise Cancellation",
            waterResistance: "IPX4",
        },
        features: [
            "Touch Controls",
            "Wireless Charging Case",
            "Voice Assistant",
        ],
        colors: ["White", "Black", "Navy"],
        mainImage: "https://m.media-amazon.com/images/I/514wYamaTxL._SL1500_.jpg",
        subImages: [
            "https://m.media-amazon.com/images/I/61TztvFfUDL._SL1500_.jpg",
            "https://m.media-amazon.com/images/I/51iXbt7++4L._SL1500_.jpg",
            "https://m.media-amazon.com/images/I/51rcZ47VLHL._SL1500_.jpg",
        ],
        description:
            "Experience premium sound quality and comfort with Wireless Earbuds Pro. Featuring active noise cancellation and long battery life.",
    },
    {
        id: 4,
        name: "Gaming Laptop X1",
        brand: "GameForce",
        category: "Laptops",
        price: 1799.99,
        currency: "USD",
        stock: 30,
        rating: 4.8,
        releaseDate: "2023-12-01",
        specs: {
            processor: "Intel Core i9-11900H",
            gpu: "NVIDIA RTX 3080",
            ram: 32,
            storage: "1TB SSD",
            display: "15.6-inch 240Hz",
            operatingSystem: "Windows 11",
        },
        features: ["RGB Keyboard", "Thunderbolt 4", "Advanced Cooling"],
        colors: ["Black", "Silver"],
        mainImage: "https://m.media-amazon.com/images/I/81PX4yLSehL._SL1500_.jpg",
        subImages: [
            "https://m.media-amazon.com/images/I/719gOCTry9L._SL1500_.jpg",
            "https://m.media-amazon.com/images/I/81RujrvAFLL._SL1500_.jpg",
            "https://m.media-amazon.com/images/I/812ZVUjeVCL._SL1500_.jpg",
        ],
        description:
            "Dominate your games with the powerful Gaming Laptop X1. Featuring top-of-the-line graphics and processing power.",
    },
    {
        id: 5,
        name: "Smartwatch Elite",
        brand: "TechCo",
        category: "Wearables",
        price: 349.99,
        currency: "USD",
        stock: 150,
        rating: 4.4,
        releaseDate: "2023-08-15",
        specs: {
            display: "1.4-inch AMOLED",
            battery: "Up to 14 days",
            waterResistance: "5 ATM",
            sensors: ["Heart Rate", "GPS", "SpO2"],
        },
        features: ["ECG Monitoring", "Sleep Tracking", "NFC Payments"],
        colors: ["Black", "Silver", "Rose Gold"],
        mainImage: "https://m.media-amazon.com/images/I/51qGlsxswZL.jpg",
        subImages: [
            "https://m.media-amazon.com/images/I/41qKKYDJUQS.jpg",
            "https://m.media-amazon.com/images/I/41cit5yP9-L.jpg",
            "https://m.media-amazon.com/images/I/41OwIDa-kXL.jpg",
        ],
        description:
            "Stay connected and monitor your health with Smartwatch Elite. Packed with advanced features for fitness enthusiasts.",
    },
    {
        id: 6,
        name: "4K Action Camera",
        brand: "AdventurePro",
        category: "Cameras",
        price: 299.99,
        currency: "USD",
        stock: 80,
        rating: 4.6,
        releaseDate: "2023-07-01",
        specs: {
            resolution: "4K/60fps",
            sensorType: "12MP CMOS",
            waterproofDepth: "10m without case",
            batteryLife: "2 hours at 4K/60fps",
        },
        features: ["Image Stabilization", "Voice Control", "Live Streaming"],
        colors: ["Black", "Blue"],
        mainImage: "https://m.media-amazon.com/images/I/61126QGucML._SL1188_.jpg",
        subImages: [
            "https://m.media-amazon.com/images/I/61LQb+KX3lL._SL1149_.jpg",
            "https://m.media-amazon.com/images/I/51tx6WC7y+L.jpg",
            "https://m.media-amazon.com/images/I/61GU5xYC3lL._SL1080_.jpg",
        ],
        description:
            "Capture your adventures in stunning 4K with this rugged action camera. Waterproof and packed with features for outdoor enthusiasts.",
    },
    {
        id: 7,
        name: "Smart Home Hub",
        brand: "ConnectEase",
        category: "Smart Home",
        price: 129.99,
        currency: "USD",
        stock: 100,
        rating: 4.3,
        releaseDate: "2023-09-30",
        specs: {
            compatibility: ["Zigbee", "Z-Wave", "Wi-Fi"],
            voice: ["Alexa", "Google Assistant"],
            display: "7-inch touchscreen",
        },
        features: [
            "Energy Monitoring",
            "Automation Routines",
            "Video Intercom",
        ],
        colors: ["White", "Black"],
        mainImage: "https://m.media-amazon.com/images/I/71sQGGy0vqL._SL1500_.jpg",
        subImages: [
            "https://m.media-amazon.com/images/I/71SQBavQRKL._SL1500_.jpg",
            "https://m.media-amazon.com/images/I/61czaDBAEYL._SL1500_.jpg",
            "https://m.media-amazon.com/images/I/71gTMwqbX+L._SL1500_.jpg",
        ],
        description:
            "Control your entire smart home from one central hub. Compatible with multiple protocols and voice assistants.",
    },
    {
        id: 8,
        name: "Wireless Gaming Mouse",
        brand: "GameForce",
        category: "Computer Accessories",
        price: 79.99,
        currency: "USD",
        stock: 200,
        rating: 4.7,
        releaseDate: "2023-11-15",
        specs: {
            dpi: "up to 20000",
            buttons: 8,
            batteryLife: "up to 70 hours",
            weight: "93g",
        },
        features: [
            "RGB Lighting",
            "On-the-fly DPI Switching",
            "Programmable Buttons",
        ],
        colors: ["Black", "White"],
        mainImage: "https://m.media-amazon.com/images/I/61qN9d08hgL._SL1500_.jpg",
        subImages: [
            "https://m.media-amazon.com/images/I/71XvZWCwEqL._SL1500_.jpg",
            "https://m.media-amazon.com/images/I/71jbPpYbShL._SL1500_.jpg",
            "https://m.media-amazon.com/images/I/61iroP64dDL._SL1500_.jpg",
        ],
        description:
            "Gain a competitive edge with this high-precision wireless gaming mouse. Customizable and built for performance.",
    },
    {
        id: 9,
        name: "Portable SSD 1TB",
        brand: "DataSpeed",
        category: "Storage",
        price: 149.99,
        currency: "USD",
        stock: 150,
        rating: 4.8,
        releaseDate: "2023-10-10",
        specs: {
            capacity: "1TB",
            interface: "USB 3.2 Gen 2",
            readSpeed: "up to 1050 MB/s",
            writeSpeed: "up to 1000 MB/s",
        },
        features: ["Shock Resistant", "Password Protection", "Compact Design"],
        colors: ["Black", "Silver", "Blue"],
        mainImage: "https://m.media-amazon.com/images/I/71T96AZDYoL._SL1500_.jpg",
        subImages: [
            "https://m.media-amazon.com/images/I/71M-k+tBOCL._SL1500_.jpg",
            "https://m.media-amazon.com/images/I/716WhkNT9+L._SL1500_.jpg",
            "https://m.media-amazon.com/images/I/71lDBhAG3FL._SL1500_.jpg",
        ],
        description:
            "Fast, compact, and durable portable SSD for on-the-go storage needs. Perfect for professionals and content creators.",
    },
    {
        id: 10,
        name: "Smart Thermostat",
        brand: "EcoControl",
        category: "Smart Home",
        price: 199.99,
        currency: "USD",
        stock: 120,
        rating: 4.5,
        releaseDate: "2023-08-20",
        specs: {
            compatibility: "Works with most HVAC systems",
            display: "3.5-inch color touchscreen",
            sensors: ["Temperature", "Humidity", "Occupancy"],
        },
        features: ["Energy Saving", "Remote Control", "Learning Capability"],
        colors: ["White", "Black", "Silver"],
        mainImage: "https://m.media-amazon.com/images/I/71tOIiqPdcL._AC_SL1500_.jpg",
        subImages: [
            "https://m.media-amazon.com/images/I/71y7peBNDIL._AC_SL1500_.jpg",
            "https://m.media-amazon.com/images/I/61uDhvyU-AL._AC_SL1252_.jpg",
            "https://m.media-amazon.com/images/I/713vPyqoJaL._AC_SL1500_.jpg",
        ],
        description:
            "Save energy and increase comfort with this smart thermostat. Learn your habits and automatically adjust for optimal efficiency.",
    },
    {
        id: 11,
        name: "Wireless Noise-Cancelling Headphones",
        brand: "AudioMax",
        category: "Audio",
        price: 299.99,
        currency: "USD",
        stock: 100,
        rating: 4.7,
        releaseDate: "2023-12-05",
        specs: {
            batteryLife: "Up to 30 hours",
            driver: "40mm dynamic",
            noiseReduction: "Active Noise Cancellation",
            connectivity: "Bluetooth 5.0",
        },
        features: [
            "Touch Controls",
            "Voice Assistant Support",
            "Foldable Design",
        ],
        colors: ["Black", "Silver", "Midnight Blue"],
        mainImage: "https://m.media-amazon.com/images/I/71OIcvhi66L._SL1500_.jpg",
        subImages: [
            "https://m.media-amazon.com/images/I/71euoJMwriL._SL1500_.jpg",
            "https://m.media-amazon.com/images/I/71FjWrXIFlL._SL1500_.jpg",
            "https://m.media-amazon.com/images/I/613b5z3It5L._SL1500_.jpg",
        ],
        description:
            "Immerse yourself in your music with these premium wireless headphones. Featuring advanced noise cancellation and superior sound quality.",
    },
    {
        id: 12,
        name: "Smart Doorbell",
        brand: "SecureHome",
        category: "Smart Home",
        price: 179.99,
        currency: "USD",
        stock: 150,
        rating: 4.4,
        releaseDate: "2023-09-01",
        specs: {
            resolution: "1080p HD",
            fieldOfView: "160 degrees",
            nightVision: "Infrared",
            powerSource: "Hardwired or Battery",
        },
        features: ["Two-way Audio", "Motion Detection", "Cloud Storage"],
        colors: ["Satin Nickel", "Venetian Bronze"],
        mainImage: "https://m.media-amazon.com/images/I/41Rqwgc+bPL._SL1074_.jpg",
        subImages: [
            "https://example.com/images/smart-doorbell-1.jpg",
            "https://m.media-amazon.com/images/I/51e5YMmX07L.jpg",
            "https://m.media-amazon.com/images/I/41b3LDyOL6L.jpg",
        ],
        description:
            "Keep your home secure with this smart doorbell. See, hear, and speak to visitors from anywhere using your smartphone.",
    },
    {
        id: 13,
        name: "Ultra-Wide Gaming Monitor",
        brand: "ViewTech",
        category: "Monitors",
        price: 899.99,
        currency: "USD",
        stock: 40,
        rating: 4.8,
        releaseDate: "2023-11-20",
        specs: {
            size: "34 inches",
            resolution: "3440x1440",
            refreshRate: 144,
            responseTime: "1ms",
            panel: "IPS",
        },
        features: ["G-Sync Compatible", "HDR400", "RGB Backlight"],
        colors: ["Black"],
        mainImage: "https://m.media-amazon.com/images/I/71M+qMtmTaL._SL1280_.jpg",
        subImages: [
            "https://m.media-amazon.com/images/I/61RStGy86bL._SL1280_.jpg",
            "https://m.media-amazon.com/images/I/51VRpXQPbWL._SL1280_.jpg",
            "https://m.media-amazon.com/images/I/61FayNax+jL._SL1280_.jpg",
        ],
        description:
            "Immerse yourself in your games with this ultra-wide curved gaming monitor. Experience smooth gameplay and vibrant colors.",
    },
    {
        id: 14,
        name: "Smart Robot Vacuum",
        brand: "CleanTech",
        category: "Home Appliances",
        price: 399.99,
        currency: "USD",
        stock: 80,
        rating: 4.6,
        releaseDate: "2023-10-15",
        specs: {
            suction: "2500Pa",
            batteryLife: "Up to 150 minutes",
            dustBinCapacity: "0.6L",
            noiseLevel: "65dB",
        },
        features: ["App Control", "Mapping Technology", "Auto-Recharge"],
        colors: ["White", "Black"],
        mainImage: "https://m.media-amazon.com/images/I/5108TYAdGES._SL1500_.jpg",
        subImages: [
            "https://m.media-amazon.com/images/I/51aMXGDL4ZS._SL1500_.jpg",
            "https://m.media-amazon.com/images/I/61Wu0PVveGS._SL1500_.jpg",
            "https://m.media-amazon.com/images/I/71Cdv8fyfgS._SL1500_.jpg",
        ],
        description:
            "Keep your floors clean effortlessly with this smart robot vacuum. Features advanced mapping and can be controlled from your smartphone.",
    },
    {
        id: 15,
        name: "Portable Bluetooth Speaker",
        brand: "AudioMax",
        category: "Audio",
        price: 129.99,
        currency: "USD",
        stock: 200,
        rating: 4.5,
        releaseDate: "2023-07-01",
        specs: {
            power: "20W",
            batteryLife: "Up to 12 hours",
            waterResistance: "IPX7",
            connectivity: "Bluetooth 5.1",
        },
        features: ["360-degree Sound", "Speakerphone", "Voice Assistant"],
        colors: ["Black", "Blue", "Red"],
        mainImage: "https://m.media-amazon.com/images/I/41PHD7hzSUL.jpg",
        subImages: [
            "https://m.media-amazon.com/images/I/51smDiMIMdL.jpg",
            "https://m.media-amazon.com/images/I/61PgZwsks5L.jpg",
            "https://m.media-amazon.com/images/I/61SQv5NQoNL.jpg",
        ],
        description:
            "Take your music anywhere with this portable Bluetooth speaker. Waterproof design and powerful sound make it perfect for outdoor use.",
    },
    {
        id: 16,
        name: "4-in-1 Wireless Charger",
        brand: "PowerUp",
        category: "Accessories",
        price: 79.99,
        currency: "USD",
        stock: 150,
        rating: 4.3,
        releaseDate: "2023-09-10",
        specs: {
            inputPower: "18W",
            wirelessOutput: "15W",
            compatibility: ["Qi-enabled devices", "Apple Watch", "AirPods"],
        },
        features: [
            "Fast Charging",
            "Multiple Device Support",
            "LED Indicators",
        ],
        colors: ["White", "Black"],
        mainImage: "https://m.media-amazon.com/images/I/31Y5McZ5pQL.jpg",
        subImages: [
            "https://m.media-amazon.com/images/I/61BPCDewJQL._SL1500_.jpg",
            "https://m.media-amazon.com/images/I/518hiXuVMSL._SL1144_.jpg",
            "https://m.media-amazon.com/images/I/61S0QEBdPxL._SL1500_.jpg",
        ],
        description:
            "Charge all your devices in one place with this 4-in-1 wireless charger. Compatible with smartphones, smartwatches, and wireless earbuds.",
    },
    {
        id: 17,
        name: "Smart WiFi Router",
        brand: "NetSpeed",
        category: "Networking",
        price: 199.99,
        currency: "USD",
        stock: 100,
        rating: 4.7,
        releaseDate: "2023-08-15",
        specs: {
            wifiStandard: "Wi-Fi 6 (802.11ax)",
            bandwidth: "AX5400",
            ports: "4 x Gigabit LAN, 1 x Gigabit WAN",
            processor: "1.5 GHz Quad-Core",
        },
        features: ["Parental Controls", "VPN Server", "MU-MIMO"],
        colors: ["Black"],
        mainImage: "https://m.media-amazon.com/images/I/51InxSS2yTL._SL1500_.jpg",
        subImages: [
            "https://m.media-amazon.com/images/I/619kZ8fqIRL._SL1000_.jpg",
            "https://m.media-amazon.com/images/I/614im4T695L._SL1000_.jpg",
            "https://m.media-amazon.com/images/I/619ocOyW03L._SL1000_.jpg",
        ],
        description:
            "Boost your home network with this powerful WiFi 6 router. Enjoy faster speeds, lower latency, and better coverage throughout your home.",
    },
    {
        id: 18,
        name: "Digital Drawing Tablet",
        brand: "ArtPro",
        category: "Computer Accessories",
        price: 249.99,
        currency: "USD",
        stock: 70,
        rating: 4.6,
        releaseDate: "2023-11-01",
        specs: {
            activeArea: "10 x 6.25 inches",
            pressureLevels: 8192,
            resolution: "5080 LPI",
            expressKeys: 8,
        },
        features: [
            "Tilt Support",
            "Wireless Capability",
            "Customizable ExpressKeys",
        ],
        colors: ["Black", "White"],
        mainImage: "https://m.media-amazon.com/images/I/71YA4YfxxXL._SL1500_.jpg",
        subImages: [
            "https://m.media-amazon.com/images/I/71+2bsClHCL._SL1500_.jpg",
            "https://m.media-amazon.com/images/I/71DRKbNhvLL._SL1500_.jpg",
            "https://m.media-amazon.com/images/I/61oHTm8hXdL._SL1000_.jpg",
        ],
        description:
            "Unleash your creativity with this professional-grade digital drawing tablet. Perfect for digital artists, designers, and photographers.",
    },
    {
        id: 19,
        name: "Smart Coffee Maker",
        brand: "BrewMaster",
        category: "Home Appliances",
        price: 149.99,
        currency: "USD",
        stock: 90,
        rating: 4.4,
        releaseDate: "2023-09-20",
        specs: {
            capacity: "12 cups",
            waterTank: "1.8L",
            brewingTime: "8 minutes",
            programmable: "24 hours",
        },
        features: [
            "Wi-Fi Connectivity",
            "Voice Control",
            "Custom Brew Strength",
        ],
        colors: ["Stainless Steel", "Black"],
        mainImage: "https://m.media-amazon.com/images/I/71eood2xIWL._AC_SL1500_.jpg",
        subImages: [
            "https://m.media-amazon.com/images/I/71dAMnrVvCL._AC_SL1500_.jpg",
            "https://m.media-amazon.com/images/I/61aVBlvfiWL._AC_SL1500_.jpg",
            "https://m.media-amazon.com/images/I/61bGqxfY6uL._AC_SL1500_.jpg",
        ],
        description:
            "Start your day right with this smart coffee maker. Control it from your phone or with your voice for the perfect cup every time.",
    },
    {
        id: 20,
        name: "Wireless Gaming Controller",
        brand: "GameForce",
        category: "Gaming Accessories",
        price: 69.99,
        currency: "USD",
        stock: 150,
        rating: 4.7,
        releaseDate: "2023-10-01",
        specs: {
            connectivity: "Bluetooth 5.0",
            batteryLife: "Up to 40 hours",
            range: "Up to 10 meters",
            vibration: "Dual motors",
        },
        features: ["Programmable Buttons", "Motion Controls", "Low Latency"],
        colors: ["Black", "White", "Red"],
        mainImage: "https://m.media-amazon.com/images/I/71BpUJ09GtL._SL1500_.jpg",
        subImages: [
            "https://m.media-amazon.com/images/I/71Ks6J78kzL._SL1500_.jpg",
            "https://m.media-amazon.com/images/I/71QQZMVQEXL._SL1500_.jpg",
            "https://m.media-amazon.com/images/I/71yyd8h5M8L._SL1500_.jpg",
        ],
        description:
            "Take control of your games with this responsive wireless controller. Compatible with multiple platforms for versatile gaming.",
    },
    {
        id: 21,
        name: "Smart Security Camera",
        brand: "SecureHome",
        category: "Smart Home",
        price: 129.99,
        currency: "USD",
        stock: 120,
        rating: 4.5,
        releaseDate: "2023-08-01",
        specs: {
            resolution: "1080p HD",
            fieldOfView: "130 degrees",
            nightVision: "Up to 30 feet",
            audioType: "Two-way",
        },
        features: ["Motion Detection", "Cloud Storage", "Weather-resistant"],
        colors: ["White", "Black"],
        mainImage: "https://m.media-amazon.com/images/I/61h6R9zMV-L._SL1234_.jpg",
        subImages: [
            "https://m.media-amazon.com/images/I/614Ii1ta8pL._SL1234_.jpg",
            "https://m.media-amazon.com/images/I/61XXXIYmBsL._SL1234_.jpg",
            "https://m.media-amazon.com/images/I/61ELfeWPRcL._SL1234_.jpg",
        ],
        description:
            "Keep an eye on your property with this smart security camera. Features night vision and two-way audio for comprehensive protection.",
    },
    {
        id: 22,
        name: "Portable Power Bank",
        brand: "PowerUp",
        category: "Accessories",
        price: 49.99,
        currency: "USD",
        stock: 200,
        rating: 4.6,
        releaseDate: "2023-07-15",
        specs: {
            capacity: "20000mAh",
            inputPorts: ["USB-C", "Micro-USB"],
            outputPorts: ["USB-C", "2 x USB-A"],
            maxOutput: "18W",
        },
        features: ["Fast Charging", "LED Power Indicator", "Compact Design"],
        colors: ["Black", "White", "Blue"],
        mainImage: "https://m.media-amazon.com/images/I/71mXM2m5SjL._SL1500_.jpg",
        subImages: [
            "https://m.media-amazon.com/images/I/718cCOp5eVS._SL1500_.jpg",
            "https://m.media-amazon.com/images/I/71rLsC0tKdL._SL1500_.jpg",
            "https://m.media-amazon.com/images/I/81AJgrNeJCL._SL1500_.jpg",
        ],
        description:
            "Never run out of battery with this high-capacity portable power bank. Charge multiple devices simultaneously on the go.",
    },
    {
        id: 23,
        name: "Smart Light Bulb Set",
        brand: "IllumiTech",
        category: "Smart Home",
        price: 79.99,
        currency: "USD",
        stock: 100,
        rating: 4.4,
        releaseDate: "2023-09-05",
        specs: {
            wattage: "9W",
            lumens: "800",
            colorTemperature: "2700K-6500K",
            lifespan: "25000 hours",
        },
        features: ["Voice Control", "Scheduling", "16 Million Colors"],
        colors: ["White"],
        mainImage: "https://m.media-amazon.com/images/I/81FsENNLg6L._SL1500_.jpg",
        subImages: [
            "https://m.media-amazon.com/images/I/81Go8S-WSPL._SL1500_.jpg",
            "https://m.media-amazon.com/images/I/81zFzxQwWaL._SL1500_.jpg",
            "https://m.media-amazon.com/images/I/81snfAbLbpL._SL1500_.jpg",
        ],
        description:
            "Transform your home lighting with this smart light bulb set. Control brightness, color, and schedules from your smartphone.",
    },
    {
        id: 24,
        name: "Ergonomic Office Chair",
        brand: "ComfortPro",
        category: "Office Furniture",
        price: 299.99,
        currency: "USD",
        stock: 50,
        rating: 4.7,
        releaseDate: "2023-10-10",
        specs: {
            material: "Mesh back, padded seat",
            adjustableHeight: "Yes",
            armrests: "3D adjustable",
            maxWeight: "300 lbs",
        },
        features: ["Lumbar Support", "Tilt Mechanism", "Breathable Mesh"],
        colors: ["Black", "Gray"],
        mainImage: "https://m.media-amazon.com/images/I/810sn8TqURL._SL1500_.jpg",
        subImages: [
            "https://m.media-amazon.com/images/I/81k7HpHxpFL._SL1500_.jpg",
            "https://m.media-amazon.com/images/I/71dLlV-SfVL._SL1500_.jpg",
            "https://m.media-amazon.com/images/I/81DNTgyx4dL._SL1500_.jpg",
        ],
        description:
            "Work comfortably for hours with this ergonomic office chair. Adjustable features ensure proper posture and support.",
    },

    {
        id: 25,
        name: "Wireless Mechanical Keyboard",
        brand: "TypeMaster",
        category: "Computer Accessories",
        price: 129.99,
        currency: "USD",
        stock: 100,
        rating: 4.6,
        releaseDate: "2023-11-15",
        specs: {
            switchType: "Cherry MX Brown",
            layout: "Full-size",
            batteryLife: "Up to 40 hours",
            connectivity: "Bluetooth 5.0 / USB-C",
        },
        features: ["RGB Backlighting", "Programmable Keys", "N-Key Rollover"],
        colors: ["Black", "White"],
        mainImage: "https://m.media-amazon.com/images/I/71RERrqR3IL._AC_SL1500_.jpg",
        subImages: [
            "https://m.media-amazon.com/images/I/71UTUr5kXdL._AC_SL1500_.jpg",
            "https://m.media-amazon.com/images/I/71HqhlBh6HL._AC_SL1500_.jpg",
            "https://m.media-amazon.com/images/I/71miGNHw+xL._AC_SL1500_.jpg",
        ],
        description:
            "Enhance your typing experience with this wireless mechanical keyboard. Featuring customizable RGB lighting and tactile switches.",
    },
    {
        id: 26,
        name: "Smart Air Purifier",
        brand: "CleanAir",
        category: "Home Appliances",
        price: 249.99,
        currency: "USD",
        stock: 80,
        rating: 4.7,
        releaseDate: "2023-09-20",
        specs: {
            coverage: "Up to 500 sq. ft.",
            filterType: "HEPA + Activated Carbon",
            cadr: "300 m³/h",
            noiseLevel: "25-52 dB",
        },
        features: ["Air Quality Sensor", "App Control", "Auto Mode"],
        colors: ["White"],
        mainImage: "https://m.media-amazon.com/images/I/51oQCJUGOeL._SL1000_.jpg",
        subImages: [
            "https://m.media-amazon.com/images/I/61NNOb4XtWL._SL1000_.jpg",
            "https://m.media-amazon.com/images/I/51KfWsduzJL._SL1000_.jpg",
            "https://m.media-amazon.com/images/I/61eoKPpq9jL._SL1000_.jpg",
        ],
        description:
            "Breathe cleaner air with this smart air purifier. Monitors air quality in real-time and adjusts settings automatically.",
    },
    {
        id: 27,
        name: "4K Streaming Media Player",
        brand: "StreamMax",
        category: "Home Entertainment",
        price: 89.99,
        currency: "USD",
        stock: 150,
        rating: 4.5,
        releaseDate: "2023-10-01",
        specs: {
            resolution: "4K HDR",
            storage: "8GB",
            processor: "Quad-core",
            remoteType: "Voice-enabled",
        },
        features: ["Dolby Atmos", "Alexa Built-in", "Dual-band Wi-Fi"],
        colors: ["Black"],
        mainImage: "https://m.media-amazon.com/images/I/61hpvCuXhpL._SL1500_.jpg",
        subImages: [
            "https://m.media-amazon.com/images/I/71fGwpn7niL._SL1500_.jpg",
            "https://m.media-amazon.com/images/I/71i3FAzOJyS._SL1500_.jpg",
            "https://m.media-amazon.com/images/I/719PcSa6QCL._SL1500_.jpg",
        ],
        description:
            "Transform your TV into a smart entertainment hub with this 4K streaming media player. Access thousands of streaming apps and games.",
    },
    {
        id: 28,
        name: "Wireless Charging Pad",
        brand: "PowerUp",
        category: "Accessories",
        price: 39.99,
        currency: "USD",
        stock: 200,
        rating: 4.4,
        releaseDate: "2023-08-10",
        specs: {
            outputPower: "15W",
            compatibility: "Qi-enabled devices",
            chargingDistance: "Up to 8mm",
            inputPort: "USB-C",
        },
        features: ["Fast Charging", "Slim Design", "LED Indicator"],
        colors: ["Black", "White"],
        mainImage: "https://m.media-amazon.com/images/I/61oIAKY9s1L._SL1500_.jpg",
        subImages: [
            "https://m.media-amazon.com/images/I/517G72RjeiL._SL1001_.jpg",
            "https://m.media-amazon.com/images/I/51aZ4fbctOL._SL1001_.jpg",
            "https://m.media-amazon.com/images/I/61pbXsTjmjL._SL1001_.jpg",
        ],
        description:
            "Charge your devices effortlessly with this sleek wireless charging pad. Compatible with all Qi-enabled smartphones and earbuds.",
    },
    {
        id: 29,
        name: "Smart Body Scale",
        brand: "HealthTrack",
        category: "Health & Fitness",
        price: 79.99,
        currency: "USD",
        stock: 120,
        rating: 4.6,
        releaseDate: "2023-11-05",
        specs: {
            maxWeight: "400 lbs / 180 kg",
            accuracy: "0.1 lb / 0.05 kg",
            metrics: ["Weight", "BMI", "Body Fat %", "Muscle Mass"],
            powerSource: "4 x AAA batteries",
        },
        features: [
            "Bluetooth Connectivity",
            "Multi-User Support",
            "Smartphone App",
        ],
        colors: ["White", "Black"],
        mainImage: "https://m.media-amazon.com/images/I/61TSqtmdJUL._SL1500_.jpg",
        subImages: [
            "https://m.media-amazon.com/images/I/61PC1OWYcmL._SL1500_.jpg",
            "https://m.media-amazon.com/images/I/61pCI9J1wuL._SL1024_.jpg",
            "https://m.media-amazon.com/images/I/61GLqFm8jVL._SL1500_.jpg",
        ],
        description:
            "Track your fitness progress with this smart body scale. Measures multiple body metrics and syncs data to your smartphone.",
    },
    {
        id: 30,
        name: "Portable Document Scanner",
        brand: "ScanPro",
        category: "Office Equipment",
        price: 129.99,
        currency: "USD",
        stock: 80,
        rating: 4.5,
        releaseDate: "2023-09-15",
        specs: {
            scanResolution: "Up to 600 dpi",
            scanSpeed: "8 seconds per page",
            fileFormats: ["PDF", "JPEG", "TIFF"],
            connectivity: "Wi-Fi / USB",
        },
        features: [
            "Automatic Document Feeder",
            "Duplex Scanning",
            "OCR Technology",
        ],
        colors: ["Gray"],
        mainImage: "https://m.media-amazon.com/images/I/51DoqL2oi9L._SL1500_.jpg",
        subImages: [
            "https://m.media-amazon.com/images/I/51ELIQ70QPL._SL1500_.jpg",
            "https://m.media-amazon.com/images/I/61UVs1mBU+L._SL1500_.jpg",
            "https://m.media-amazon.com/images/I/51DoqL2oi9L._SL1500_.jpg",
        ],
        description:
            "Digitize your documents on the go with this portable scanner. Features wireless connectivity and OCR for searchable PDFs.",
    },
    {
        id: 31,
        name: "Smart Sous Vide Cooker",
        brand: "ChefTech",
        category: "Kitchen Appliances",
        price: 199.99,
        currency: "USD",
        stock: 70,
        rating: 4.7,
        releaseDate: "2023-10-20",
        specs: {
            powerOutput: "1000W",
            temperatureRange: "32°F to 197°F (0°C to 92°C)",
            pumpCirculation: "2.1 GPM",
            containerCapacity: "Up to 20L",
        },
        features: [
            "Wi-Fi Connectivity",
            "Precision Temperature Control",
            "Recipe App",
        ],
        colors: ["Black", "Silver"],
        mainImage: "https://m.media-amazon.com/images/I/61mzKAht5IL._AC_SL1500_.jpg",
        subImages: [
            "https://m.media-amazon.com/images/I/61OK5aLr5WL._AC_SL1345_.jpg",
            "https://m.media-amazon.com/images/I/61sgngJOhkL._AC_SL1500_.jpg",
            "https://m.media-amazon.com/images/I/71-sbtQfHbL._AC_SL1500_.jpg",
        ],
        description:
            "Achieve restaurant-quality results at home with this smart sous vide cooker. Control and monitor your cooking from your smartphone.",
    },
    {
        id: 32,
        name: "Wireless Presenter Remote",
        brand: "PresentPro",
        category: "Office Accessories",
        price: 39.99,
        currency: "USD",
        stock: 150,
        rating: 4.4,
        releaseDate: "2023-08-01",
        specs: {
            range: "Up to 100 feet",
            batteryLife: "Up to 6 months",
            compatibility: "Windows, macOS, Linux",
            buttons: 5,
        },
        features: ["Laser Pointer", "Volume Control", "Plug-and-Play"],
        colors: ["Black"],
        mainImage: "https://m.media-amazon.com/images/I/51Pb10N15XL._SL1200_.jpg",
        subImages: [
            "https://m.media-amazon.com/images/I/61BTlcdCSFL._SL1200_.jpg",
            "https://m.media-amazon.com/images/I/61Kwa8t18lL._SL1200_.jpg",
            "https://m.media-amazon.com/images/I/61ydeIentxL._SL1200_.jpg",
        ],
        description:
            "Take control of your presentations with this wireless remote. Features an intuitive design and long-range connectivity.",
    },
    {
        id: 33,
        name: "Smart Pet Feeder",
        brand: "PetCare",
        category: "Pet Accessories",
        price: 149.99,
        currency: "USD",
        stock: 100,
        rating: 4.6,
        releaseDate: "2023-11-10",
        specs: {
            capacity: "6L",
            portions: "1/8 cup to 4 cups",
            scheduledMeals: "Up to 12 per day",
            powerSource: "DC adapter with battery backup",
        },
        features: ["App Control", "HD Camera", "Two-Way Audio"],
        colors: ["White", "Gray"],
        mainImage: "https://m.media-amazon.com/images/I/7189WieJUYL._SL1500_.jpg",
        subImages: [
            "https://m.media-amazon.com/images/I/613Tr5zyH2L._SL1500_.jpg",
            "https://m.media-amazon.com/images/I/61g8HVMvOvL._SL1500_.jpg",
            "https://m.media-amazon.com/images/I/71soZvSgKvL._SL1500_.jpg",
        ],
        description:
            "Keep your pet fed on schedule with this smart pet feeder. Monitor and interact with your pet remotely using the built-in camera.",
    },
    {
        id: 34,
        name: "Portable Photo Printer",
        brand: "PrintMaster",
        category: "Printers",
        price: 129.99,
        currency: "USD",
        stock: 90,
        rating: 4.5,
        releaseDate: "2023-09-01",
        specs: {
            printTechnology: "ZINK (Zero Ink)",
            printResolution: "313 x 400 dpi",
            printSize: "2 x 3 inches",
            connectivity: "Bluetooth, NFC",
        },
        features: [
            "Smartphone App",
            "Rechargeable Battery",
            "Water-Resistant Prints",
        ],
        colors: ["White", "Pink", "Blue"],
        mainImage: "https://m.media-amazon.com/images/I/61oXUJa8WML._SL1500_.jpg",
        subImages: [
            "https://m.media-amazon.com/images/I/81cuzzczbXL._SL1500_.jpg",
            "https://m.media-amazon.com/images/I/81fBtErhECL._SL1500_.jpg",
            "https://m.media-amazon.com/images/I/712-fKcomWL._SL1500_.jpg",
        ],
        description:
            "Print your memories instantly with this portable photo printer. Create sticker-backed prints directly from your smartphone.",
    },
    {
        id: 35,
        name: "Smart Bike Lock",
        brand: "SecureCycle",
        category: "Outdoor & Sports",
        price: 99.99,
        currency: "USD",
        stock: 120,
        rating: 4.4,
        releaseDate: "2023-10-05",
        specs: {
            lockType: "U-Lock",
            material: "Hardened Steel",
            batteryLife: "Up to 6 months",
            unlockMethods: ["Smartphone App", "Keypad"],
        },
        features: ["GPS Tracking", "Tamper Alerts", "Share Access"],
        colors: ["Black"],
        mainImage: "https://m.media-amazon.com/images/I/71yTWEKY2BL._SL1500_.jpg",
        subImages: [
            "https://m.media-amazon.com/images/I/819h+1cx3PL._SL1500_.jpg",
            "https://m.media-amazon.com/images/I/71fhJTq43cL._SL1500_.jpg",
            "https://m.media-amazon.com/images/I/71t8V5VOc8L._SL1500_.jpg",
        ],
        description:
            "Secure your bike with this smart lock. Unlock with your smartphone, track your bike's location, and receive alerts if tampering is detected.",
    },
    {
        id: 36,
        name: "Dual-Monitor Arm",
        brand: "ErgoPro",
        category: "Office Accessories",
        price: 159.99,
        currency: "USD",
        stock: 80,
        rating: 4.7,
        releaseDate: "2023-08-15",
        specs: {
            compatibleSize: "13 to 32 inches",
            maxWeight: "17.6 lbs per arm",
            vesa: "75x75mm, 100x100mm",
            adjustability: "360° rotation, +90°/-90° tilt, 180° swivel",
        },
        features: [
            "Gas Spring System",
            "Cable Management",
            "Tool-Free Assembly",
        ],
        colors: ["Black", "Silver"],
        mainImage: "https://m.media-amazon.com/images/I/61+cDhOq7dL._SL1500_.jpg",
        subImages: [
            "https://m.media-amazon.com/images/I/81Gcpj95x-S._SL1500_.jpg",
            "https://m.media-amazon.com/images/I/818YDctY1PS._SL1500_.jpg",
            "https://m.media-amazon.com/images/I/8128QIqjOiS._SL1500_.jpg",
        ],
        description:
            "Optimize your workspace with this dual-monitor arm. Easily adjust your monitors for improved ergonomics and productivity.",
    },
];

localStorage.setItem("e-com_product-data",JSON.stringify(products))
